// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_borrow = lv_imgbtn_create(ui_Screen1);
    lv_obj_set_height(ui_borrow, 50);
    lv_obj_set_width(ui_borrow, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_borrow, 400);
    lv_obj_set_y(ui_borrow, 100);
    lv_obj_set_align(ui_borrow, LV_ALIGN_CENTER);

    ui_return = lv_imgbtn_create(ui_Screen1);
    lv_obj_set_height(ui_return, 50);
    lv_obj_set_width(ui_return, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_return, 400);
    lv_obj_set_y(ui_return, 200);
    lv_obj_set_align(ui_return, LV_ALIGN_CENTER);

    ui_Textarera = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_Textarera, 600);
    lv_obj_set_height(ui_Textarera, 200);
    lv_obj_set_x(ui_Textarera, 212);
    lv_obj_set_y(ui_Textarera, 349);
    lv_obj_set_align(ui_Textarera, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_Textarera, "\nPRESS IT!");
    lv_textarea_set_placeholder_text(ui_Textarera, "Placeholder...");
    lv_obj_set_style_text_align(ui_Textarera, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Textarera, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_emoj1_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, -128);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_borrow, ui_event_borrow, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_return, ui_event_return, LV_EVENT_ALL, NULL);

}
