// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void emoji_Animation(lv_obj_t * TargetObject, int delay);
void word_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
void ui_event_borrow(lv_event_t * e);
extern lv_obj_t * ui_borrow;
void ui_event_return(lv_event_t * e);
extern lv_obj_t * ui_return;
extern lv_obj_t * ui_Textarera;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_emoj1_png);    // assets/emoj1.png
LV_IMG_DECLARE(ui_img_emoj2_png);    // assets/emoj2.png
LV_IMG_DECLARE(ui_img_emoj3_png);    // assets/emoj3.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
